name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'ci'
      - 'perf'
      - 'refactor'
      - 'security'
      - 'test'
  - title: 'Documentation'
    labels:
      - 'docs'
  - title: 'Dependency Updates'
    labels:
      - 'dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels:
  - 'skip-changelog'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feat'
      - 'feature'
  patch:
    labels:
      - 'patch'
  default: patch

autolabeler:
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'ci'
    branch:
      - '/ci\/.+/'
  - label: 'dependencies'
    branch:
      - '/dependencies\/.+/'
  - label: 'docs'
    branch:
      - '/docs\/.+/'
  - label: 'feature'
    branch:
      - '/feat(ure)?\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
  - label: 'perf'
    branch:
      - '/perf\/.+/'
  - label: 'refactor'
    branch:
      - '/refactor\/.+/'
  - label: 'security'
    branch:
      - '/security\/.+/'
  - label: 'test'
    branch:
      - '/test\/.+/'

template: |
  # What's Changed

  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION